---
- name: Deploy DevStack
  hosts: openstack_vm
  become: yes

  pre_tasks:
    - name: Include variables
      include_vars:
        file: group_vars/all.yml

  tasks:
    - name: Create stack user
      user:
        name: "{{ stack_user }}"
        shell: /bin/bash
        home: "{{ stack_home }}"
        create_home: yes
        state: present

    - name: Ensure stack home directory has correct permissions
      file:
        path: "{{ stack_home }}"
        mode: '0755'
        owner: "{{ stack_user }}"
        group: "{{ stack_user }}"

    - name: Add stack user to sudoers
      copy:
        dest: /etc/sudoers.d/stack
        content: "stack ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'

    - name: Create environment file for stack user
      template:
        src: templates/bash_profile.j2
        dest: "{{ stack_home }}/.bash_profile"
        owner: "{{ stack_user }}"
        group: "{{ stack_user }}"
        mode: '0644'

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Switch to stack user
      become: yes
      become_user: "{{ stack_user }}"
      shell: |
        whoami
      register: current_user
      
    - name: Debug current user
      debug:
        var: current_user.stdout

    - name: Clone DevStack repository
      become: yes
      become_user: "{{ stack_user }}"
      git:
        repo: "{{ devstack_repo }}"
        dest: "{{ stack_home }}/devstack"
        force: no
      register: git_clone_result

    - name: Debug git clone
      debug:
        var: git_clone_result

    # Ensure proper ownership of the devstack directory
    - name: Ensure devstack directory ownership
      file:
        path: "{{ stack_home }}/devstack"
        owner: "{{ stack_user }}"
        group: "{{ stack_user }}"
        recurse: yes
        state: directory
      when: git_clone_result.changed

    - name: Create local.conf
      template:
        src: templates/local.conf.j2
        dest: "{{ stack_home }}/devstack/local.conf"
        owner: "{{ stack_user }}"
        group: "{{ stack_user }}"
        mode: '0644'
    
    - name: Verify stack user before installation
      become: yes
      become_user: "{{ stack_user }}"
      shell: |
        echo "Current user: $(whoami)"
        echo "Current directory: $(pwd)"
        echo "Home directory: $HOME"
      register: user_check
      
    - name: Debug user verification
      debug:
        var: user_check.stdout_lines

    - name: Run stack.sh
      become: yes
      become_user: "{{ stack_user }}"
      shell: |
        cd {{ stack_home }}/devstack && ./stack.sh
      environment:
        HOME: "{{ stack_home }}"
        USER: "{{ stack_user }}"
      async: 3600  # Allow up to 1 hour for installation
      poll: 0
      register: stack_result

    - name: Check stack.sh progress
      become: yes
      become_user: "{{ stack_user }}"
      async_status:
        jid: "{{ stack_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 360  # Check every 10 seconds for 1 hour
      delay: 10
      environment:
        HOME: "{{ stack_home }}"
        USER: "{{ stack_user }}"
